# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
