# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 19:50
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0004_auto_20160919_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=redactor.fields.RedactorField(verbose_name='Body Text'),
        ),
    ]
