# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 16:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0005_auto_20160919_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
