# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0007_article_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='header',
        ),
    ]
