# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0008_remove_article_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.URLField(default='', verbose_name='header image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name="slug (autogenerates, don't mess with this)"),
        ),
    ]
