# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0009_auto_20160922_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='bylinelink',
            field=models.URLField(default='', verbose_name="Byline Link (please link to author's IW byline page)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.URLField(verbose_name='header Image URL (900px by 300px)'),
        ),
    ]
