# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0010_auto_20160922_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default='', verbose_name='auto_now'),
            preserve_default=False,
        ),
    ]
