# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0012_auto_20160923_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
